title: "hey. you found my portfolio. glad you're here"
description: "you'll find things i do when i'm bored"
baseurl: ""
url: "https://n4hu3lj.github.io"

theme: jekyll-theme-console

# pags que aparecen en la barra superior
header_pages:
  - index.md
  - about.md

# estilos: dark, light, hacker, nord
style: dark
listen_for_clients_preferred_style: true

# pie de pag
footer: '$watchmore <a href="https://github.com/n4hu3lj" target="_blank">GitHub</a>'

disable_google_fonts: true

plugins:
  - jekyll-seo-tag

# compresion de CSS con Sass
sass:
  style: compressed

